name: Pull Request
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Test
        run: go test -v
  send-message:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: print github context
        run: echo "${{ toJson(github) }}"
