name: Pull Request
on: pull_request
jobs:
  send-message:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Send Message
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "# Message with markdown.\nThis is the message that will be displayed on users' first issue."
          pr-message: "Message that will be displayed on users' first pr. Look, a `code block` for markdown."
